//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lib_K_Relay.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lib_K_Relay.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Objects&gt;
        ///  &lt;Object type=&quot;0x0715&quot; id=&quot;Decoy&quot;&gt;
        ///    &lt;Class&gt;Character&lt;/Class&gt;
        ///    &lt;AnimatedTexture&gt;
        ///      &lt;File&gt;players&lt;/File&gt;
        ///      &lt;Index&gt;11&lt;/Index&gt;
        ///    &lt;/AnimatedTexture&gt;
        ///    &lt;Friendly /&gt;
        ///    &lt;CanUseTexes /&gt;
        ///    &lt;NoMiniMap /&gt;
        ///  &lt;/Object&gt;
        ///  &lt;Object type=&quot;0x755f&quot; id=&quot;Dire Decoy&quot;&gt;
        ///    &lt;Class&gt;Character&lt;/Class&gt;
        ///    &lt;Texture&gt;
        ///      &lt;File&gt;d3LofiObjEmbed&lt;/File&gt;
        ///      &lt;Index&gt;0x2c&lt;/Index&gt;
        ///    &lt;/Texture&gt;
        ///    &lt;Friendly /&gt;
        ///    &lt;NoMiniMap /&gt;
        ///  &lt;/Object&gt;
        ///  &lt;Object type=&quot;0xb101&quot; id=&quot;G [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Objects {
            get {
                return ResourceManager.GetString("Objects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;Packets&gt;
        ///    &lt;Packet id=&quot;FAILURE&quot; type=&quot;0&quot;/&gt;
        ///    &lt;Packet id=&quot;CREATE_SUCCESS&quot; type=&quot;101&quot;/&gt;
        ///    &lt;Packet id=&quot;CREATE&quot; type=&quot;61&quot;/&gt;
        ///    &lt;Packet id=&quot;PLAYERSHOOT&quot; type=&quot;30&quot;/&gt;
        ///    &lt;Packet id=&quot;MOVE&quot; type=&quot;42&quot;/&gt;
        ///    &lt;Packet id=&quot;PLAYERTEXT&quot; type=&quot;10&quot;/&gt;
        ///    &lt;Packet id=&quot;TEXT&quot; type=&quot;44&quot;/&gt;
        ///    &lt;Packet id=&quot;SERVERPLAYERSHOOT&quot; type=&quot;12&quot;/&gt;
        ///    &lt;Packet id=&quot;DAMAGE&quot; type=&quot;75&quot;/&gt;
        ///    &lt;Packet id=&quot;UPDATE&quot; type=&quot;62&quot;/&gt;
        ///    &lt;Packet id=&quot;UPDATEACK&quot; type=&quot;81&quot;/&gt;
        ///    &lt;Packet id=&quot;NOTIFICATION&quot; type=&quot;67 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Packets {
            get {
                return ResourceManager.GetString("Packets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Servers&gt;&lt;Server&gt;&lt;Name&gt;~Proxy Server~&lt;/Name&gt;&lt;DNS&gt;127.0.0.1&lt;/DNS&gt;&lt;Lat&gt;0&lt;/Lat&gt;&lt;Long&gt;0&lt;/Long&gt;&lt;Usage&gt;0.75&lt;/Usage&gt;&lt;/Server&gt;.
        /// </summary>
        internal static string ProxyServer {
            get {
                return ResourceManager.GetString("ProxyServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///
        ///&lt;Servers&gt;
        ///    &lt;Server&gt;
        ///        &lt;Name&gt;USEast2&lt;/Name&gt;
        ///        &lt;DNS&gt;52.87.248.5&lt;/DNS&gt;
        ///        &lt;Lat&gt;42.89&lt;/Lat&gt;
        ///        &lt;Long&gt;-78.88&lt;/Long&gt;
        ///        &lt;Usage&gt;0.00&lt;/Usage&gt;
        ///    &lt;/Server&gt;
        ///    &lt;Server&gt;
        ///        &lt;Name&gt;EUEast&lt;/Name&gt;
        ///        &lt;DNS&gt;18.184.218.174&lt;/DNS&gt;
        ///        &lt;Lat&gt;54.69&lt;/Lat&gt;
        ///        &lt;Long&gt;25.28&lt;/Long&gt;
        ///        &lt;Usage&gt;0.00&lt;/Usage&gt;
        ///    &lt;/Server&gt;
        ///    &lt;Server&gt;
        ///        &lt;Name&gt;EUSouthWest&lt;/Name&gt;
        ///        &lt;DNS&gt;35.180.67.120&lt;/DNS&gt;
        ///        &lt;Lat&gt;48.86&lt;/Lat&gt;
        ///        &lt;Long&gt;2.35&lt;/L [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Servers {
            get {
                return ResourceManager.GetString("Servers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;GroundTypes&gt;
        ///    &lt;Ground type=&quot;0xb005&quot; id=&quot;Abyss Lava&quot;&gt;
        ///        &lt;Texture&gt;
        ///            &lt;File&gt;abyssOfDemonsObjects8x8&lt;/File&gt;
        ///            &lt;Index&gt;0x03&lt;/Index&gt;
        ///        &lt;/Texture&gt;
        ///        &lt;MinDamage&gt;60&lt;/MinDamage&gt;
        ///        &lt;MaxDamage&gt;60&lt;/MaxDamage&gt;
        ///        &lt;Animate dx=&quot;.33&quot; dy=&quot;.33&quot;&gt;Flow&lt;/Animate&gt;
        ///        &lt;Sink/&gt;
        ///        &lt;Speed&gt;.666&lt;/Speed&gt;
        ///        &lt;Color&gt;0xF2711A&lt;/Color&gt;
        ///    &lt;/Ground&gt;
        ///    &lt;Ground type=&quot;0xb004&quot; id=&quot;Abyss Volcanic Tile&quot;&gt;
        ///        &lt;RandomTexture&gt;
        ///            &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Tiles {
            get {
                return ResourceManager.GetString("Tiles", resourceCulture);
            }
        }
    }
}
